# Generated by Django 5.2.5 on 2025-08-28 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='courses.course'),
        ),
        migrations.AddField(
            model_name='lead',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.branch'),
        ),
        migrations.AddField(
            model_name='application',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.lead'),
        ),
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.organization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.branch'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.organization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('lead', 'course')},
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['organization', 'name'], name='core_branch_organiz_3d15ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('organization', 'name')},
        ),
    ]
