# Generated by Django 5.2.5 on 2025-08-27 14:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('skill', models.CharField(choices=[('grammar', 'Grammar'), ('vocab', 'Vocabulary'), ('reading', 'Reading'), ('listening', 'Listening')], default='grammar', max_length=12)),
                ('cefr_hint', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('audio_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('estimated_level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('raw_payload', models.JSONField(default=dict)),
                ('ua', models.CharField(blank=True, max_length=200)),
                ('ip_hash', models.CharField(blank=True, max_length=128)),
                ('skill_breakdown', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='placement.placementquestion')),
            ],
        ),
    ]
