# Generated by Django 5.2.5 on 2025-08-26 16:59

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_override', models.CharField(blank=True, max_length=140, verbose_name='Başlık (Web)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama (Web)')),
                ('address_override', models.CharField(blank=True, max_length=255, verbose_name='Adres (Web)')),
                ('phone_override', models.CharField(blank=True, max_length=40, verbose_name='Telefon (Web)')),
                ('email_override', models.EmailField(blank=True, max_length=254, verbose_name='E-posta (Web)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=website.models.branch_image_upload_path)),
                ('photo_alt', models.CharField(blank=True, max_length=160, verbose_name='Görsel ALT')),
                ('map_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem')),
                ('map_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam')),
                ('map_embed_url', models.URLField(blank=True, verbose_name='Harita Embed URL')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Yayında')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_profile', to='core.branch')),
            ],
            options={
                'verbose_name': 'Şube (Web)',
                'verbose_name_plural': 'Şubeler (Web)',
                'ordering': ['sort_order', 'branch__name'],
                'indexes': [models.Index(fields=['is_visible', 'sort_order'], name='website_bra_is_visi_bda971_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_override', models.CharField(blank=True, max_length=120, verbose_name='Unvan (Web)')),
                ('bio_public', models.TextField(blank=True, verbose_name='Kısa Biyografi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=website.models.teacher_image_upload_path)),
                ('photo_alt', models.CharField(blank=True, max_length=160, verbose_name='Foto ALT')),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Yayında')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profiles', to='core.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profiles', to='core.organization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_profiles', to='staffs.teacher')),
            ],
            options={
                'verbose_name': 'Öğretmen Profili',
                'verbose_name_plural': 'Öğretmen Profilleri',
                'ordering': ['sort_order', 'teacher__last_name'],
                'indexes': [models.Index(fields=['organization', 'is_visible', 'sort_order'], name='website_tea_organiz_7e477b_idx'), models.Index(fields=['organization', 'branch', 'is_visible'], name='website_tea_organiz_a0d3bb_idx')],
                'unique_together': {('organization', 'slug')},
            },
        ),
    ]
