# Generated by Django 5.2.5 on 2025-08-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitem',
            name='description',
            field=models.TextField(default=dict, help_text='Kursuň giňişleýin açyklamasy', verbose_name='Açyklama'),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='name',
            field=models.CharField(default=dict, verbose_name='Sapagyň kurs adlandyrmalary'),
        ),
    ]
