# Generated by Django 5.2.5 on 2025-08-26 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_subject'),
        ('website', '0002_courseitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseitem',
            options={'verbose_name': 'Kurs (Web)', 'verbose_name_plural': 'Kurslar (Web)'},
        ),
        migrations.RemoveField(
            model_name='courseitem',
            name='course',
        ),
        migrations.AddField(
            model_name='courseitem',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.subject', verbose_name='Sapagyň ady'),
            preserve_default=False,
        ),
    ]
