# Generated by Django 5.2.5 on 2025-08-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_courseitem_description_alter_courseitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitem',
            name='description',
            field=models.JSONField(default=dict, help_text='Kursuň giňişleýin açyklamasy', verbose_name='Açyklama'),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='name',
            field=models.JSONField(default=dict, verbose_name='Sapagyň kurs adlandyrmalary'),
        ),
    ]
