# Generated by Django 5.2.5 on 2025-08-27 05:54

import django.db.models.deletion
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('courses', '0003_alter_course_subject'),
        ('website', '0003_alter_courseitem_options_remove_courseitem_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseitem',
            options={'verbose_name': 'Okuw (Web)', 'verbose_name_plural': 'Okuwlar (Web)'},
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Sapagyň kurs adlandyrmalary'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Başlık')),
                ('body', models.TextField(blank=True, verbose_name='İçerik')),
                ('link_url', models.URLField(blank=True, verbose_name='Bağlantı')),
                ('audience', models.CharField(choices=[('PUBLIC', 'Public (Herkes)'), ('STUDENTS', 'Öğrenciler'), ('TEACHERS', 'Öğretmenler'), ('ENROLLED', 'Kayıtlı Öğrenciler'), ('STAFF', 'Personel')], db_index=True, default='PUBLIC', max_length=10, verbose_name='Hedef')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('SCHEDULED', 'Zamanlanmış'), ('PUBLISHED', 'Yayında'), ('ARCHIVED', 'Arşiv')], db_index=True, default='DRAFT', max_length=10, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('INFO', 'Bilgi'), ('SUCCESS', 'Başarılı'), ('WARNING', 'Uyarı'), ('DANGER', 'Acil')], db_index=True, default='INFO', max_length=10, verbose_name='Öncelik')),
                ('pinned', models.BooleanField(default=False, verbose_name='Üste Sabitle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('publish_start_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Başlangıcı')),
                ('publish_end_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Bitişi')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='core.branch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.organization')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-pinned', '-publish_start_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=website.models.announcement_upload_to)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='website.announcement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=website.models.announcement_upload_to)),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='Başlık/Alt Yazı')),
                ('alt', models.CharField(blank=True, max_length=160, verbose_name='Alt Metin (SEO/erişilebilirlik)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.announcement')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['audience', 'status', 'is_active'], name='website_ann_audienc_937f66_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['branch', 'course'], name='website_ann_branch__4d5560_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['pinned', 'priority'], name='website_ann_pinned_21491d_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementimage',
            index=models.Index(fields=['announcement', 'order'], name='website_ann_announc_f8dd1c_idx'),
        ),
    ]
