# Generated by Django 5.2.5 on 2025-08-27 08:44

import django.db.models.deletion
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('courses', '0003_alter_course_subject'),
        ('website', '0004_alter_courseitem_options_alter_courseitem_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('link_url', models.URLField(blank=True, verbose_name='Dış Bağlantı')),
                ('audience', models.CharField(choices=[('PUBLIC', 'Public (Herkes)'), ('STUDENTS', 'Öğrenciler'), ('TEACHERS', 'Öğretmenler'), ('ENROLLED', 'Kayıtlı Öğrenciler'), ('STAFF', 'Personel')], db_index=True, default='PUBLIC', max_length=10, verbose_name='Hedef')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('SCHEDULED', 'Zamanlanmış'), ('PUBLISHED', 'Yayında'), ('CANCELLED', 'İptal'), ('ARCHIVED', 'Arşiv')], db_index=True, default='DRAFT', max_length=10, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('INFO', 'Bilgi'), ('SUCCESS', 'Başarılı'), ('WARNING', 'Uyarı'), ('DANGER', 'Acil')], db_index=True, default='INFO', max_length=10, verbose_name='Öncelik')),
                ('pinned', models.BooleanField(default=False, verbose_name='Üste Sabitle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='Başlangıç')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('publish_start_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Başlangıcı')),
                ('publish_end_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Bitişi')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online')),
                ('meeting_url', models.URLField(blank=True, verbose_name='Toplantı Linki')),
                ('venue_name', models.CharField(blank=True, max_length=160, verbose_name='Mekân Adı')),
                ('venue_address', models.TextField(blank=True, verbose_name='Adres')),
                ('venue_city', models.CharField(blank=True, max_length=80, verbose_name='Şehir')),
                ('venue_room', models.CharField(blank=True, max_length=80, verbose_name='Salon/No')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kapasite')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.branch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.organization')),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'ordering': ['-pinned', 'start_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=website.models.event_upload_to)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='website.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=website.models.event_upload_to)),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='Başlık/Alt Yazı')),
                ('alt', models.CharField(blank=True, max_length=160, verbose_name='Alt Metin (SEO/erişilebilirlik)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.event')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['audience', 'status', 'is_active'], name='website_eve_audienc_6178bb_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['branch', 'course'], name='website_eve_branch__212028_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_at'], name='website_eve_start_a_c1f737_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['pinned', 'priority'], name='website_eve_pinned_6fc936_idx'),
        ),
        migrations.AddIndex(
            model_name='eventimage',
            index=models.Index(fields=['event', 'order'], name='website_eve_event_i_c98e75_idx'),
        ),
    ]
