# Generated by Django 5.2.4 on 2025-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AG_app', '0004_news_alter_teachers_last_name_alter_teachers_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='activity/')),
            ],
        ),
    ]
