# Generated by Django 5.2.5 on 2025-08-18 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AG_app', '0004_activity_adress_contacts_examevents_examvenues_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='AG_app.branch'),
        ),
    ]
