# Generated by Django 5.2.4 on 2025-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AG_app', '0005_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%Y/%M')),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='photo',
            new_name='image',
        ),
    ]
