# Generated by Django 5.2.5 on 2025-08-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AG_app', '0006_alter_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=40, unique=True, verbose_name='Telefon'),
        ),
    ]
