# Generated by Django 5.2.4 on 2025-08-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AG_app', '0006_video_rename_photo_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('number', models.CharField(max_length=50)),
            ],
        ),
    ]
