# Generated by Django 5.2.4 on 2025-08-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AG_app', '0008_course_course_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_item',
            new_name='CourseItem',
        ),
    ]
