# Generated by Django 5.2.4 on 2025-08-14 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AG_app', '0009_rename_course_item_courseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AG_app.course'),
        ),
    ]
