# Generated by Django 5.2.4 on 2025-08-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AG_app', '0010_alter_courseitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='photo',
            new_name='image',
        ),
    ]
