# Generated by Django 5.2.4 on 2025-08-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AG_app', '0011_rename_photo_activity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=50)),
                ('course_level', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('course_location', models.CharField(max_length=200)),
                ('certificate', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='adress',
            old_name='number',
            new_name='phone_num',
        ),
    ]
