# Generated by Django 5.2.4 on 2025-08-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AG_app', '0012_certificate_rename_number_adress_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='phone_num',
            field=models.IntegerField(default='+99', max_length=10),
        ),
    ]
