# Generated by Django 5.2.4 on 2025-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AG_app', '0014_alter_certificate_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='phone_num',
            field=models.CharField(default='+993', max_length=12),
        ),
    ]
