# Generated by Django 5.2.4 on 2025-08-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AG_app', '0015_alter_certificate_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('upper', 'Upper'), ('advanced', 'Advanced')], default='Tapgyryny sayla', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course_location',
            field=models.CharField(choices=[('mary merkez', 'Merkez Şahamçasy, Mary ş.'), ('shapak', 'Şapak Şahamçasy, Mary ş.'), ('miras', 'Miras Şahamçasy, Mary ş.'), ('yoloten', 'Ýolöten Şahamçasy, Ýolöten ş.')], default='Kurs ýeri', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course_name',
            field=models.CharField(choices=[('english', 'Iňlis dili'), ('russian', 'Rus dili'), ('math', 'Matematika'), ('computer', 'Kompýuter')], default='Kurs adyny saýla', max_length=200),
        ),
    ]
