# Generated by Django 5.2.4 on 2025-08-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AG_app', '0016_alter_certificate_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Upper', 'Upper'), ('Advanced', 'Advanced')], default='Tapgyryny sayla', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course_location',
            field=models.CharField(choices=[('Merkez Şahamçasy, Mary ş.', 'Merkez Şahamçasy, Mary ş.'), ('Şapak Şahamçasy, Mary ş.', 'Şapak Şahamçasy, Mary ş.'), ('Miras Şahamçasy, Mary ş.', 'Miras Şahamçasy, Mary ş.'), ('Ýolöten Şahamçasy, Ýolöten ş.', 'Ýolöten Şahamçasy, Ýolöten ş.')], default='Kurs ýeri', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course_name',
            field=models.CharField(choices=[('Iňlis dili', 'Iňlis dili'), ('Rus dili', 'Rus dili'), ('Matematika', 'Matematika'), ('Kompýuter', 'Kompýuter')], default='Kurs adyny saýla', max_length=200),
        ),
    ]
