# Generated by Django 5.2.5 on 2025-08-23 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=80, verbose_name='Soyad')),
                ('title', models.CharField(blank=True, help_text='Örn: Almanca Eğitmeni', max_length=80, verbose_name='Unvan')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=40, unique=True, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Tam Zamanlı'), ('PART_TIME', 'Yarı Zamanlı'), ('CONTRACT', 'Sözleşmeli'), ('FREELANCE', 'Freelance')], default='FULL_TIME', max_length=12, verbose_name='Çalışma Tipi')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('ON_LEAVE', 'İzinde'), ('INACTIVE', 'Pasif'), ('LEFT', 'Ayrıldı')], default='ACTIVE', max_length=10, verbose_name='Durum')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='İşe Başlama')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='Ayrılış')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Saatlik Ücret')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Hakkında')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='core.branch', verbose_name='Şube')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='courses.subject', verbose_name='Verdiği Konular')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Mugallym',
                'verbose_name_plural': 'Mugallymlar',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='staffs_teac_last_na_e93091_idx'), models.Index(fields=['branch', 'status'], name='staffs_teac_branch__b5f6f1_idx')],
            },
        ),
    ]
