# Generated by Django 5.2.5 on 2025-08-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('courses', '0004_alter_attendance_options'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Örn: Matematik - Trigonometri', max_length=200)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=80)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_url', models.URLField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('repeat_every', models.PositiveIntegerField(default=1, help_text='Hafta sayısı (1=her hafta)')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='courses.course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='staffs.teacher')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimetableException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cancelled', models.BooleanField(default=False)),
                ('override_start_time', models.TimeField(blank=True, null=True)),
                ('override_end_time', models.TimeField(blank=True, null=True)),
                ('override_room', models.CharField(blank=True, max_length=80)),
                ('override_meeting_url', models.URLField(blank=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='schedule.timetableentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['day_of_week', 'start_time'], name='schedule_ti_day_of__6a752a_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['is_active'], name='schedule_ti_is_acti_edcf64_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['course'], name='schedule_ti_course__2152ee_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['branch'], name='schedule_ti_branch__e25fec_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['teacher'], name='schedule_ti_teacher_41a3f5_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableexception',
            index=models.Index(fields=['entry', 'date'], name='schedule_ti_entry_i_513ada_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableexception',
            unique_together={('entry', 'date')},
        ),
    ]
