# Generated by Django 5.2.5 on 2025-08-21 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('courses', '0001_initial'),
        ('staffs', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='staffs.teacher', verbose_name='Eğitmen'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='material',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course'),
        ),
        migrations.AddField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.branch'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='courses.room'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name', 'level'], name='courses_sub_name_a3cebc_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='courses_sub_is_acti_7c6ad7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'level')},
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.subject', verbose_name='Konu'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['assessment', 'student'], name='courses_ass_assessm_7f1b93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentresult',
            unique_together={('assessment', 'student')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['session', 'student'], name='courses_att_session_6438a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('session', 'student')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'student', 'status'], name='courses_enr_course__cb7169_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('course', 'student')},
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['branch', 'name'], name='courses_roo_branch__f77f24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('branch', 'name')},
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['course', 'date'], name='courses_cla_course__a94bab_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'is_active'], name='courses_cou_status_fa8151_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['branch', 'start_date'], name='courses_cou_branch__f3a63c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject', 'teacher'], name='courses_cou_subject_1b187a_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('start_date__isnull', False)), fields=('branch', 'subject', 'teacher', 'start_date'), name='uniq_course_per_branch_subject_teacher_start'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'student'], name='courses_sub_assignm_6a633f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student')},
        ),
    ]
