# Generated by Django 5.2.5 on 2025-08-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.JSONField(default=dict, verbose_name='Ders Adı'),
        ),
    ]
