# Generated by Django 5.2.5 on 2025-08-29 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsession',
            options={'ordering': ['start_at'], 'verbose_name': 'Sapak sagady', 'verbose_name_plural': 'Sapak sagatlary (class session)'},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='marked_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='method',
            field=models.CharField(choices=[('face', 'Face'), ('card', 'Card'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='note',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='courses_att_status_fdae4e_idx'),
        ),
    ]
