# Generated by Django 5.2.5 on 2025-08-23 19:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['branch', 'name'], 'verbose_name': 'Sınıf/Oda', 'verbose_name_plural': 'Sınıflar/Odalar'},
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, max_length=60, verbose_name='Bina'),
        ),
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Oda Kodu'),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='features',
            field=models.JSONField(blank=True, default=list, verbose_name='Özellikler'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kat'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.branch', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kapasite'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Oda Adı'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['branch', 'is_active'], name='courses_roo_branch__fedab6_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('code', None), _negated=True), fields=('branch', 'code'), name='uniq_room_code_per_branch'),
        ),
    ]
