# Generated by Django 5.2.5 on 2025-08-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_classsession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Gatnaşyk', 'verbose_name_plural': 'Gatnaşyklar (Ýoklama)'},
        ),
    ]
